name: 🐞 Bug report
description: Create a report to help us reproduce and fix the bug
title: "[Bug] "
labels: ['Bug']

body:
- type: checkboxes
  attributes:
    label: Checklist
    options:
    - label: I have searched related issues.
    - label: The bug has not been fixed in the latest version.
    - label: Bug-related environment info are given.
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Reproduction
    description: |
      What command or script did you run? Which **model** are you using?
    placeholder: |
      A placeholder for the command.
  validations:
    required: true
- type: textarea
  attributes:
    label: Output
    description: |
      Please provide the full output log of the bug.
    placeholder: |
      A placeholder for the log.
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment
    description: |
      Please provide necessary environment information here with `python3 print_env.py`.
    placeholder: Environment here.
  validations:
    required: true